#!/usr/bin/perl 

use lib ('.', '..');

use strict;
use warnings;
use Getopt::Long;
use JSON; 

use PVE::Tools;
use PVE::HA::Sim::Hardware;

my $testdir;

if (!GetOptions ("test=s"   => \$testdir)) {
    print "usage: $0 [--test=<dir>]\n";
    exit -1;
}

if ($testdir) {

    my $hardware = PVE::HA::Sim::Hardware->new($testdir);

    $hardware->log('err', "starting simulation");

    eval { $hardware->run(); };
    if (my $err = $@) {
	$hardware->log('err', "exit simulation - $err ");
    } else {
	$hardware->log('info', "exit simulation - done");
    }

    exit(0);
   
} else {
    # my $statusdir; = "/var/tmp/pve-ha-manager";
    die "implement me";
}



