#!/usr/bin/perl 

use lib ('.', '..');

use strict;
use warnings;
use Getopt::Long;
  
use PVE::Tools;
use PVE::HA::SimEnv;
use PVE::HA::Server;

my $testdir;

if (!GetOptions ("test=s"   => \$testdir)) {
    print "usage: $0 [--test=<dir>]\n";
    exit -1;
}

my $haenv;

if ($testdir) {

    $haenv = PVE::HA::SimEnv->new($testdir);

} else {
    # my $statusdir; = "/var/tmp/pve-ha-manager";
    die "implement me";
}

if (!$haenv->manager_status_exists()) {
    $haenv->log('info', "HA is not enabled");
    exit(0);
}

$haenv->log('info', "starting server");

my $server = PVE::HA::Server->new($haenv);

eval {

    for (;;) {

	last if !$server->do_one_iteration();

    }
};
if (my $err = $@) {
    $haenv->log('err', "exit server - $err ");
} else {
    $haenv->log('info', "exit server - done");
}

exit(0);

