#!/usr/bin/perl

use strict;
use warnings;

use PVE::Cluster;
use PVE::CLI::ha_manager;

my $prepare = sub {
    PVE::Cluster::check_cfs_is_mounted();
    PVE::Cluster::cfs_update();
};
    
PVE::CLI::ha_manager->run_cli(undef, undef, $prepare);
